### ISSUE TITLE
Unwrap causing panic

### ISSUE THREAD

**Issue by Devlyn-Nelson** [TsuITOAR/visa-rs#22] opened 2024-06-19 18:13 UTC
When a device is not present in the system and I try to connect via TCP using `DefaultRM::new()?.open() `, visa-rs panics with a 0xBFFF0011 error which should just be returned as an `visa-rs::Error` because the function already returns a result contain that error type. The root cause of the panic is an `unwrap` after a `try_into` in the `wrap_raw_error_in_unsafe` macro.

**Comment by Devlyn-Nelson** [comment] 2024-06-19 20:01
I should say I am willing to do work in order to fix this. I have a workaround currently working. there are 2 problems:
- In `wrap_raw_error_in_unsafe`  any status code greater than 0 is considered Success but `0xBFFF0011` is not a success condition.
- the `repr` for `ErrorCode` fails to translate `0xBFFF0011` into a valid variant even though it is valid.

**Comment by TsuITOAR** [comment] 2024-07-06 10:33
Thanks for your response, I will check this problem ASAP.

**Comment by TsuITOAR** [comment] 2024-07-07 09:02
On my PC, it returns the Error `ErrorRsrcNfound` (error code `0xBFFF0011`) as expected, this problem might be related to your specific environment.
`0xBFFF0011` is a negative number, so it should match the Error arm in the macro.
Here are codes that I tried.
```rust
use std::ffi::CString;

use visa_rs::{prelude::*, vs::ViStatus};

fn main() -> visa_rs::Result<()> {
    let res = CString::new("TCPIP0::192.168.3.1::hislip0::INSTR")
        .unwrap()
        .into();
    let r = DefaultRM::new()?.open(&res, AccessMode::NO_LOCK, TIMEOUT_IMMEDIATE);
    if let Result::Err(e) = r {
        eprintln!("Returned error in rust: `{}`", e);
        eprintln!("Error code: `{:#0X}`", e.0 as ViStatus);
    }
    Ok(())
}
```
Output
```
Returned error in rust: `Insufficient location information or the device or resource is not present in the system.`
Error code: `0xBFFF0011`
```
Feel free to ask if you want more help.

**Comment by Devlyn-Nelson** [comment] 2024-07-19 16:59
Sorry for not seeing this sooner, github decided to notify me today.

So I created a new rust project, added `visa-rs` as a dependency, and replaced the `main.rs` with the code you provided above and I get
```
thread 'main' panicked at /home/dev/.cargo/registry/src/index.crates.io-6f17d22bba15001f/visa-rs-0.6.1/s
rc/lib.rs:391:9:
called `Result::unwrap()` on an `Err` value: TryFromPrimitiveError { number: 3221159953 }
```

I do want to mention we are running this on various Linux distros, but I don't know why that would matter because I wrote a proc_macro library which generates code that converts numbers into enums and it works on every system we have tried. If you have any recommendations on where I should be looking to work in a better fix. I did look around but got lost in the macros and had to get back to other priorities.

**Comment by TsuITOAR** [comment] 2024-07-19 17:18
Are you doing some cross compilation? 
Can you check the size of `Error` and the size of `ViStatus`? 
The repr of the Error is a [proc-macro](https://github.com/TsuITOAR/visa-rs/blob/5fc5267784dd9bec8a664b5bff36425b33dad26a/src/enums/status.rs#L11), and might cause an error if you are doing some  cross compilation. The proc-macro works by checking ths size of the target repr and a legal repr ident on current platform, like [this](https://github.com/TsuITOAR/visa-rs/blob/5fc5267784dd9bec8a664b5bff36425b33dad26a/visa-rs-proc/src/repr.rs#L101C1-L144C2).

**Comment by Devlyn-Nelson** [comment] 2024-07-19 17:23
I'm assuming you want the result of `std::mem::size_of` on those and i get 8 for both.

**Comment by TsuITOAR** [comment] 2024-07-19 17:33
> I'm assuming you want the result of `std::mem::size_of` on those and i get 8 for both.

Then the repr is not the problem, and the number should be legal for a 8-byte-wide enum, wierd. 
Can you convert the `ErrorCode::ErrorRsrcNfound` to a number and check its value?

**Comment by Devlyn-Nelson** [comment] 2024-07-19 17:37
`ErrorCode::ErrorRsrcNfound as i32 = 0xBFFF0011`

**Comment by TsuITOAR** [comment] 2024-07-19 17:50
On my platform the `ViStatus` is 4-byte-wide, but 0xBFFF0011 as an 8-byte-wide number doesn't start with 1 (BIN), so it's a positive number. I thought it would fill with 1 at the start bits but seems it doesn't.
Can you try these codes?

```rs
use std::ffi::CString;

use visa_rs::{
    prelude::*,
    session::AsRawSs,
    vs::{self, ViStatus},
};

fn main() -> visa_rs::Result<()> {
    let res = CString::new("TCPIP0::192.168.3.1::hislip0::INSTR").unwrap();
    let rm = DefaultRM::new()?;
    let mut instr: vs::ViSession = 0;
    let s: ViStatus = unsafe {
        vs::viOpen(
            rm.as_raw_ss(),
            res.as_ptr(),
            AccessMode::NO_LOCK.bits(),
            TIMEOUT_IMMEDIATE.as_millis() as _,
            &mut instr as _,
        )
    };
    println!("{},{},{:#0X}", s > 0, s, s);
    Ok(())
}


```
My output
```
false,-1073807343,0xBFFF0011
```

This would be ridiculous because comparing with 0 is used in NI-VISA official examples.

**Comment by Devlyn-Nelson** [comment] 2024-07-19 18:09
My result:
```
true,3221159953,0xBFFF0011
```

I wouldn't be surprised if the NI stuff was not the greatest. I volunteer for an [FRC](https://www.firstinspires.org/robotics/frc), which makes heavy use of NI systems, and every year I have to deal with them makes my feelings about them more and more negative.

**Comment by TsuITOAR** [comment] 2024-07-19 18:17
A easy fix would be change the condition in the 'warp_raw _error_in_unsafe' from 's>=0' to 's>=0&&s<u32::MAX'. 
Can you check this solution? 
I will update the crate if it works.

**Comment by Devlyn-Nelson** [comment] 2024-07-19 18:46
It did not work, I'm playing around with the logic there to check if there is a simple why to avoid the unwraps. I think the macro's inherent ambiguity is making it a little tricky.

**Comment by Devlyn-Nelson** [comment] 2024-07-19 19:35
So my friend, who has asked that I get this working for him, told me that he can't get this compiling on windows at all. But what confuses me is that you say you are receiving a `i32` for `ViStatus` and my friend says it being a `i32` is want causes the compile error. So I must ask if you are using windows because according to [this](https://doc.rust-lang.org/std/os/raw/type.c_long.html) that would make sense. But that doesn't explain why your machine doesn't get compile errors or panics and we get a panic or a compile error depending on the system. not sure if this is the entire problem but due to the type of `ViStatus` being ambiguous, I have to imagine either NI or the translation is messy.

**Comment by Devlyn-Nelson** [comment] 2024-07-19 20:09
I redact the windows not compiling. That was my fault in the temp fix i did.

**Comment by TsuITOAR** [comment] 2024-07-20 03:14
Added some unwarp info to show which arm panicked.

```rs
#[doc(hidden)]
#[macro_export]
macro_rules! wrap_raw_error_in_unsafe {
    ($s:expr) => {
        match unsafe { $s } {
            state if state >= $crate::SUCCESS && state <= i32::MAX => {
                $crate::Result::<$crate::enums::status::CompletionCode>::Ok(
                    state.try_into().expect(&format!(
                        "Converting `{state}({state:#0X})` to CompletionCode failed"
                    )),
                )
            }
            e => $crate::Result::<$crate::enums::status::CompletionCode>::Err(
                e.try_into()
                    .expect(&format!("Converting `{e}({e:#0X})` to ErrorCode failed")),
            ),
        }
    };
}
```

And some tests to confirm the behavior of converting status codes

```rs
use crate::enums::status::{CompletionCode, ErrorCode};
    use crate::vs;

    #[test]
    fn convert_status_codes() {
        assert_eq!(
            CompletionCode::try_from(0 as vs::ViStatus).unwrap(),
            CompletionCode::Success
        );
        assert_eq!(
            ErrorCode::try_from(0xBFFF0011u32 as vs::ViStatus).unwrap(),
            ErrorCode::ErrorRsrcNfound
        );
    }

    #[test]
    #[should_panic]
    fn convert_wrong_status1() {
        CompletionCode::try_from(ErrorCode::ErrorRsrcNfound as vs::ViStatus).unwrap();
    }
    #[test]
    #[should_panic]
    fn convert_wrong_status2() {
        ErrorCode::try_from(CompletionCode::Success as vs::ViStatus).unwrap();
    }
```

**Comment by Devlyn-Nelson** [comment] 2024-07-23 21:25
So the new `wrap_raw_error_in_unsafe` function does this to a simple open program:
```
thread 'main' panicked at /home/dev/code/pumpkin/tests/visa-rs/src/lib.rs:396:9:
Converting `3221159953(0xBFFF0011)` to ErrorCode failed: TryFromPrimitiveError { number: 3221159953 }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```


And the tests you provided resulted with 
```
running 3 tests
test convert_wrong_status1 - should panic ... ok
test convert_status_codes ... FAILED
test convert_wrong_status2 - should panic ... ok

failures:

---- convert_status_codes stdout ----
thread 'convert_status_codes' panicked at tests/new.rs:11:60:
called `Result::unwrap()` on an `Err` value: TryFromPrimitiveError { number: 3221159953 }
```

From what i can tell, windows returns a i32 from windows and a i64 for linux. Problem is, the i64 is just the normal i32 output and the "un-needed" bytes are all zero regardless of correctness.

Windows outputs : "0xBFFF0011"
Linux outputs : "0x00000000_BFFF0011"

This "real" fix would be for NI to understand the basics of two's compliment or to not use ambigous types (isize) for their API. Because API changes are typically hated, NI filling the added 0s with 1s when it is negitive instead would be best.

As for solutions I can think of, maybe manually converting it to a i32 by dropping the bytes that are incorrect then converting it back to an i64. I tested this code and it seems to work.
```

#[doc(hidden)]
#[macro_export]
macro_rules! wrap_raw_error_in_unsafe {
    ($s:expr) => {
        {
            #[cfg(not(target_os = "windows"))]
            let s = {
                let thing = unsafe { $s }.to_le_bytes();
                let new_array = [thing[0], thing[1], thing[2], thing[3]];
                i32::from_le_bytes(new_array) as i64
            };
            #[cfg(target_os = "windows")]
            let s = unsafe { $s };
            match s {
                state if state >= $crate::SUCCESS && state <= i32::MAX as _ => {
                    $crate::Result::<$crate::enums::status::CompletionCode>::Ok(
                        state.try_into().expect(&format!(
                            "Converting `{state}({state:#0X})` to CompletionCode failed"
                        )),
                    )
                }
                e => $crate::Result::<$crate::enums::status::CompletionCode>::Err(
                    e.try_into()
                        .expect(&format!("Converting `{e}({e:#0X})` to ErrorCode failed")),
                ),
            }
        }
    };
}
```

**Comment by TsuITOAR** [comment] 2024-07-24 04:34
> So the new `wrap_raw_error_in_unsafe` function does this to a simple open program:
> ```
> thread 'main' panicked at /home/dev/code/pumpkin/tests/visa-rs/src/lib.rs:396:9:
> Converting `3221159953(0xBFFF0011)` to ErrorCode failed: TryFromPrimitiveError { number: 3221159953 }
> note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
> ```
> 
> 
> And the tests you provided resulted with 
> ```
> running 3 tests
> test convert_wrong_status1 - should panic ... ok
> test convert_status_codes ... FAILED
> test convert_wrong_status2 - should panic ... ok
> 
> failures:
> 
> ---- convert_status_codes stdout ----
> thread 'convert_status_codes' panicked at tests/new.rs:11:60:
> called `Result::unwrap()` on an `Err` value: TryFromPrimitiveError { number: 3221159953 }
> ```
> 
> From what i can tell, windows returns a i32 from windows and a i64 for linux. Problem is, the i64 is just the normal i32 output and the "un-needed" bytes are all zero regardless of correctness.
> 
> Windows outputs : "0xBFFF0011"
> Linux outputs : "0x00000000_BFFF0011" (should be 0xFFFFFFFF_BFFF0011)
> 
> This "real" fix would be for NI to understand the basics of two's compliment or to not use ambigous types (isize) for their API. Because API changes are typically hated, NI filling the added 0s with 1s when it is negitive instead would be best.
> 
> As for solutions I can think of, maybe manually converting it to a i32 by dropping the bytes that are incorrect then converting it back to an i64. I tested this code and it seems to work.
> ```
> 
> #[doc(hidden)]
> #[macro_export]
> macro_rules! wrap_raw_error_in_unsafe {
>     ($s:expr) => {
>         {
>             #[cfg(not(target_os = "windows"))]
>             let s = {
>                 let thing = unsafe { $s }.to_le_bytes();
>                 let new_array = [thing[0], thing[1], thing[2], thing[3]];
>                 i32::from_le_bytes(new_array) as i64
>             };
>             #[cfg(target_os = "windows")]
>             let s = unsafe { $s };
>             match s {
>                 state if state >= $crate::SUCCESS && state <= i32::MAX as _ => {
>                     $crate::Result::<$crate::enums::status::CompletionCode>::Ok(
>                         state.try_into().expect(&format!(
>                             "Converting `{state}({state:#0X})` to CompletionCode failed"
>                         )),
>                     )
>                 }
>                 e => $crate::Result::<$crate::enums::status::CompletionCode>::Err(
>                     e.try_into()
>                         .expect(&format!("Converting `{e}({e:#0X})` to ErrorCode failed")),
>                 ),
>             }
>         }
>     };
> }
> ```

Thanks, I'll check this solution.

**Comment by TsuITOAR** [comment] 2024-08-02 18:21
The problem is from the macro `consts_to_enum` I write to generate the enums.
In rust, a number is default to be i32 if not clarified, and I define enums like this 
```
ErrorRsrcNfound = 0xBFFF0011 as _
```
And if convert a i32 to i64 that starts with bit 1, the i64 number will fill 1 in all new bits, so that we will get a number that is not consistent with the visa library returned to us. 
After I remove the `as _`, problem is solved for linux. 
The fix has been uploaded to `crates.io`.

**Closed** 2024-08-02 18:29 UTC
